SUMMARY = "RAUC update bundle for Foyer OS"
DESCRIPTION = "Packages the OS rootfs and its container image seed into a \
single signed .raucb. Installing it writes the inactive root slot and its \
paired seed slot together; the config and data partitions are untouched."
LICENSE = "MIT"
# Required once SRC_URI is non-empty (the hook script below).
LIC_FILES_CHKSUM = "file://${COMMON_LICENSE_DIR}/MIT;md5=0835ade698e0bcf8506ecda2f7b4f302"

inherit bundle

RAUC_BUNDLE_COMPATIBLE = "${MACHINE}"
RAUC_BUNDLE_VERSION = "${DISTRO_VERSION}"
RAUC_BUNDLE_DESCRIPTION = "${DISTRO_NAME} ${DISTRO_VERSION}"

# "verity" rather than the legacy plain format: it allows streaming installs
# and verifies the payload as it is read rather than all up front.
RAUC_BUNDLE_FORMAT = "verity"

RAUC_BUNDLE_SLOTS = "rootfs seed"

RAUC_SLOT_rootfs = "foyer-image"
RAUC_SLOT_rootfs[fstype] = "ext4"
RAUC_SLOT_rootfs[hooks] = "post-install"

RAUC_SLOT_seed = "foyer-seed-image"
RAUC_SLOT_seed[fstype] = "ext4"
RAUC_SLOT_seed[hooks] = "post-install"

# Writing an ext4 slot replaces its superblock, wiping the filesystem label that
# grub and foyer-seed-mount look the slot up by. The hook puts it back — without
# it an updated slot is simply unbootable. See the script for the detail.
# The hook runs on the *target* during installation, so e2label has to be in
# the image — see foyer-fs-layout's RDEPENDS, not this recipe's.
SRC_URI = "file://foyer-bundle-hook.sh"
RAUC_BUNDLE_HOOKS[file] = "foyer-bundle-hook.sh"

# Signing material, generated by scripts/foyer-rauc-dev-ca (development) or
# scripts/foyer-rauc-prod-ca (production). Deliberately not in the repo; see
# the comment in recipes-core/rauc/rauc-conf.bbappend.
FOYER_RAUC_PKI_DIR ??= "${TOPDIR}/foyer-pki"

python () {
    import os
    pki_dir = d.getVar('FOYER_RAUC_PKI_DIR')
    # foyer-rauc-prod-ca's two-tier layout: the root (ca.cert.pem) only ever
    # signs signing.cert.pem, which does the actual bundle signing. Prefer it
    # when present, and fall back to foyer-rauc-dev-ca's single-tier ca.*
    # otherwise, so an existing dev PKI dir keeps working unchanged.
    signing_key = os.path.join(pki_dir, 'signing.key.pem')
    signing_cert = os.path.join(pki_dir, 'signing.cert.pem')
    dev_key = os.path.join(pki_dir, 'ca.key.pem')
    dev_cert = os.path.join(pki_dir, 'ca.cert.pem')

    # Register both candidate keys as parse dependencies *before* deciding
    # which to use (or whether to skip). Without this, the choice is baked
    # into bitbake's parse cache, and generating/rotating a CA afterwards
    # does not invalidate it — the recipe keeps using the old answer until
    # something unrelated forces a re-parse.
    bb.parse.mark_dependency(d, signing_key)
    bb.parse.mark_dependency(d, dev_key)

    if os.path.exists(signing_key):
        key, cert = signing_key, signing_cert
    elif os.path.exists(dev_key):
        key, cert = dev_key, dev_cert
    else:
        raise bb.parse.SkipRecipe(
            "No RAUC signing key in %s. Run meta-foyer/scripts/foyer-rauc-dev-ca "
            "(development) or meta-foyer/scripts/foyer-rauc-prod-ca <dir> "
            "(production), then rebuild." % pki_dir)

    d.setVar('RAUC_KEY_FILE', key)
    d.setVar('RAUC_CERT_FILE', cert)
}
