SUMMARY = "RAUC update bundle for Foyer OS"
DESCRIPTION = "Packages the OS rootfs and its container image seed into a \
single signed .raucb. Installing it writes the inactive root slot and its \
paired seed slot together; the config and data partitions are untouched."
LICENSE = "MIT"
# Required once SRC_URI is non-empty (the hook script below).
LIC_FILES_CHKSUM = "file://${COMMON_LICENSE_DIR}/MIT;md5=0835ade698e0bcf8506ecda2f7b4f302"

inherit bundle

RAUC_BUNDLE_COMPATIBLE = "${MACHINE}"
RAUC_BUNDLE_VERSION = "${DISTRO_VERSION}"
RAUC_BUNDLE_DESCRIPTION = "${DISTRO_NAME} ${DISTRO_VERSION}"

# "verity" rather than the legacy plain format: it allows streaming installs
# and verifies the payload as it is read rather than all up front.
RAUC_BUNDLE_FORMAT = "verity"

RAUC_BUNDLE_SLOTS = "rootfs seed"

RAUC_SLOT_rootfs = "foyer-image"
RAUC_SLOT_rootfs[fstype] = "ext4"
RAUC_SLOT_rootfs[hooks] = "post-install"

RAUC_SLOT_seed = "foyer-seed-image"
RAUC_SLOT_seed[fstype] = "ext4"
RAUC_SLOT_seed[hooks] = "post-install"

# Writing an ext4 slot replaces its superblock, wiping the filesystem label that
# grub and foyer-seed-mount look the slot up by. The hook puts it back — without
# it an updated slot is simply unbootable. See the script for the detail.
# The hook runs on the *target* during installation, so e2label has to be in
# the image — see foyer-fs-layout's RDEPENDS, not this recipe's.
SRC_URI = "file://foyer-bundle-hook.sh"
RAUC_BUNDLE_HOOKS[file] = "foyer-bundle-hook.sh"

# Signing material, generated by scripts/foyer-rauc-dev-ca. Deliberately not in
# the repo; see the comment in recipes-core/rauc/rauc-conf.bbappend.
FOYER_RAUC_PKI_DIR ??= "${TOPDIR}/foyer-pki"
RAUC_KEY_FILE ?= "${FOYER_RAUC_PKI_DIR}/ca.key.pem"
RAUC_CERT_FILE ?= "${FOYER_RAUC_PKI_DIR}/ca.cert.pem"

python () {
    import os
    key = d.getVar('RAUC_KEY_FILE')
    # Register the key as a parse dependency *before* deciding to skip.
    # Without this the skip is baked into bitbake's parse cache, and generating
    # the CA afterwards does not invalidate it — the recipe stays skipped until
    # something unrelated forces a re-parse.
    bb.parse.mark_dependency(d, key)
    if not os.path.exists(key):
        raise bb.parse.SkipRecipe(
            "No RAUC signing key at %s. Run meta-foyer/scripts/foyer-rauc-dev-ca "
            "to generate a development CA, then rebuild." % key)
}
